### ISSUE TITLE
Certificate outdated

### ISSUE THREAD

**Issue by AlexandreDey** [sec51/clamav-yara#3]
https://sec51.com/definitions/main.cvd certificate expired on January 2017, thus clamav-yara can't proceed

**Comment by silenteh** [comment]
@AlexandreDey Thanks for reporting the problem and sorry for the delay. I have just noticed the issue today unfortunately. 😞 
I have made sure the letsencrypt certificates get renewed automatically. Randomly the renewal failed.
There were also other issues with the format of the Clamav definition files.
Should work now, but the best is actually to host clamav files on your servers if you use this conversion utility.
